// src/pages/index.tsx
import axios from 'axios'
import Link from 'next/link'
import $rules from '@/assets/$rules'
import { useRouter } from 'next/router'
import { useUtils } from '@/assets/utils'
import { Project } from '@/types/Projects'
import { useEffect, useState } from 'react'
import { DeleteOutlined, EyeOutlined } from '@ant-design/icons'
import {
  Button,
  Form,
  Input,
  Modal,
  Popconfirm,
  Space,
  Table,
  Typography,
} from 'antd'

export default function Home() {
  const { showError } = useUtils()
  const [abrirModal, setAbrirModal] = useState(false)
  const [form] = Form.useForm()
  const router = useRouter()
  const [datos, setDatos] = useState<Project[]>([])

  const init = async () => {
    const { data } = await axios.get('/api/projects')
    setDatos(data)
  }

  const onSubmit = async (values: Project) => {
    try {
      const { data } = await axios.post<Project>('/api/projects', values)
      form.resetFields()
      router.push('/' + data.id)
    } catch (err) {
      showError(err)
    }
  }

  useEffect(() => {
    init()
  }, [])

  return (
    <div>
      <Modal
        title="Insertar"
        open={abrirModal}
        width={400}
        onOk={() => form.submit()}
        onCancel={() => setAbrirModal(false)}
      >
        <Form
          layout="horizontal"
          form={form}
          labelCol={{ span: 5 }}
          wrapperCol={{ span: 19 }}
          onFinish={onSubmit}
        >
          <Form.Item label="Título" rules={[$rules.required()]} name="titulo">
            <Input placeholder="Ingresa el título del proeycto" />
          </Form.Item>
        </Form>
      </Modal>

      <div className="flex justify-between">
        <Typography.Title>Proyectos</Typography.Title>
        <Button type="primary" onClick={() => setAbrirModal(true)}>
          Insertar
        </Button>
      </div>

      <Table
        dataSource={datos}
        rowKey="id"
        columns={[
          { title: 'ID', align: 'right', dataIndex: 'id' },
          { title: 'Título', dataIndex: 'titulo' },
          {
            align: 'center',
            width: 1,
            render: (_, row) => (
              <Space.Compact size="small">
                <Link href={'/' + row.id}>
                  <Button title="Ver proyecto" icon={<EyeOutlined />} />
                </Link>
                <Popconfirm
                  title="Eliminar proyecto"
                  description="¿Seguro que desea eliminar?"
                  onConfirm={async () => {
                    try {
                      await axios.delete('/api/projects', {
                        params: { id: row.id },
                      })
                      await init()
                    } catch (err) {
                      showError(err)
                    }
                  }}
                  okText="Yes"
                  cancelText="No"
                >
                  <Button title="Eliminar" icon={<DeleteOutlined />} />
                </Popconfirm>
              </Space.Compact>
            ),
          },
        ]}
      />
    </div>
  )
}

// pages/index.vue
<template>
  <div>
    <section class="hero is-dark">
      <div class="hero-body">
        <div class="container">
          <h1 class="title">
            <nuxt-link to="/">
              Carvers Suite
            </nuxt-link>
          </h1>
          <h2 class="subtitle">
            Suite de recuperación de archivos
          </h2>
        </div>
      </div>
    </section>
    <section class="section">
      <div class="container">
        <div class="columns">
          <div class="column">
            <h1 class="title">
              Proyectos
            </h1>
          </div>
          <div class="column">
            <b-field grouped position="is-right">
              <div class="control">
                <button
                  class="button"
                  @click="add"
                >
                  Insertar
                </button>
              </div>
            </b-field>
          </div>
        </div>
        <b-table
          :data="data"
          paginated
          per-page="20"
        >
          <template slot-scope="props">
            <b-table-column
              field="id"
              label="ID"
              width="150"
            >
              {{ props.row.id }}
            </b-table-column>
            <b-table-column field="titulo" label="Título">
              {{ props.row.titulo }}
            </b-table-column>
            <b-table-column
              centered
              field="options"
              label="Opciones"
              width="1"
            >
              <div class="buttons has-addons is-centered">
                <nuxt-link
                  :to="`/${props.row.id}`"
                  class="button is-small"
                >
                  <b-icon
                    size="is-small"
                    icon="eye"
                  />
                </nuxt-link>
                <button
                  class="button is-small"
                  @click="remove(props.row.id)"
                >
                  <b-icon
                    size="is-small"
                    icon="delete"
                  />
                </button>
              </div>
            </b-table-column>
          </template>
        </b-table>
      </div>
    </section>
  </div>
</template>

<script>
export default {
  name: 'HomePage',
  data: () => ({
    data: [],
  }),
  async created () {
    await this.init()
  },
  methods: {
    async init () {
      try {
        this.data = await this.$axios.$get('/api/projects')
      } catch (err) {
        this.$toast.open({ message: err.message, type: 'is-danger' })
      }
    },
    add () {
      this.$dialog.prompt({
        type: 'is-dark',
        message: 'Nombre del proyecto',
        confirmText: 'Añadir',
        cancelText: 'Cancelar',
        inputAttrs: { placeholder: 'Ingrese el nombre del proyecto' },
        onConfirm: value => this.sendToServer(value)
      })
    },
    async sendToServer (titulo) {
      try {
        const { id } = await this.$axios.$post('/api/projects', { titulo })
        this.$router.push(`/${id}`)
      } catch (err) {
        this.$toast.open({ message: err.message, type: 'is-danger' })
      }
    },
    remove (id) {
      this.$dialog.confirm({
        message: '¿Eliminar proyecto?',
        onConfirm: async () => {
          try {
            await this.$axios.$delete(`/api/projects/${id}`)
            await this.init()
          } catch (err) {
            this.$toast.open({ message: err.message, type: 'is-danger' })
          }
        }
      })
    }
  },
}
</script>
